<h1>Přidání nového atleta</h1>

<form method="POST" enctype="multipart/form-data">
    
    <div>
        <label for="name">Jméno atleta</label>
        <input type="text" name="name" id="name" required>
    </div>
    
    <div>
        <label for="country">Zeme</label>
        <input type="text" name="country" id="country" required>
    </div>

    <button name="newstudentForm">Vytvořit studenta</button>
</form>