<h1>Registrace</h1>

<form method="POST" enctype="multipart/form-data">
    <div>
        <label for="username">Přihlašovací jméno</label>
        <input type="text" name="username" id="username" required>
    </div>

    <div>
        <label for="password">Heslo</label>
        <input type="password" name="password" id="password" required>
    </div>

    <div>
        <label for="confirmPassword">Heslo znovu</label>
        <input type="password" name="confirmPassword" id="confirmPassword" required>
    </div>

    <div>
        <label for="email">Zadej email</label>
        <input type="email" name="email" id="email" required>
    </div>

    <div>
        <label for="role">Zadej roli</label>
        <input type="text" name="role" id="role" required>
    </div>

    <button name="registerForm">Registrovat</button>
</form>